[ES-834]
mosip/id-authentication pull request #1206
Opened 2024-02-26 08:21 UTC by pvsaidurga

2024-02-26 10:33 UTC, ase-101 commented on authentication/esignet-integration-impl/src/test/java/io/mosip/authentication/esignet/integration/service/IdaAuditPluginImplTest.java
> +//        Mockito.when(restTemplate.exchange(
if it's not required can we not delete the lines instead of commenting @pvsaidurga

2024-02-26 10:33 UTC, ase-101 commented on authentication/esignet-integration-impl/src/test/java/io/mosip/authentication/esignet/integration/service/IdaAuditPluginImplTest.java
> +//        Mockito.when(restTemplate.exchange(
if it's not required can we not delete the lines instead of commenting @pvsaidurga

2024-02-26 10:33 UTC, ase-101 commented on authentication/esignet-integration-impl/src/test/java/io/mosip/authentication/esignet/integration/service/IdaAuditPluginImplTest.java
> +//                Mockito.any(RequestEntity.class),
if it's not required can we not delete the lines instead of commenting @pvsaidurga

2024-02-26 10:34 UTC, ase-101 requested changes
Please check comments

2024-02-28 09:21 UTC, LoganathanSekar7627 approved these changes

2024-02-28 09:22 UTC, merged