Develop
mosip/id-authentication pull request #1304
Opened 2024-07-25 11:54 UTC by Anuranjan14

2024-08-14 10:45 UTC, Sohandey requested changes
Please correct this testcase 
:
apitest/src/main/resources/ida/UpdateDraft/UpdateDraft.yml

2024-08-14 11:47 UTC, Sohandey approved these changes

2024-08-28 04:14 UTC, lsivanand reviewed
You shouldn't have secret key values in the kernel properties.. Values should be empty

2024-09-02 11:37 UTC, ckm007 approved these changes

2024-09-02 12:46 UTC, merged