[PER-44]: IDA performance test scripts and supporting files
mosip/id-authentication pull request #1330
Opened 2024-09-09 07:59 UTC by nihallakshmankonchady

The following files are added under this PR.
1. IDA_Test_Script.jmx : Performance script for IDA
2. Support files : add_identity_request_details.csv, biometrics_data.txt, center_machine_id_values.csv
3. README.md : ReadMe file for IDA script execution

2024-09-09 08:46 UTC, akhilmoogi commented
@nihallakshmankonchady In readme file, mention about the token expiration details.

2024-09-09 08:47 UTC, akhilmoogi commented
@nihallakshmankonchady In Third Party Certificates (Setup) thread group, check the naming conventions.

2024-09-19 04:59 UTC, nihallakshmankonchady commented
@akhilmoogi . PR changes were made.

2024-09-19 07:45 UTC, akhilmoogi commented
@vishwa-vyom Peer review is complete for IDA. Kindly do a final review from your side and merge the PR.

2024-10-09 07:04 UTC, akhilmoogi commented
S03 Authentication with Demo (Preparation) -> Get Record From ID Repo Endpoint - > Extract Bio Value: variable name is not following naming convention

2024-10-09 07:09 UTC, akhilmoogi commented
S02 Authentication with Biometrics (Preparation) - > Loop count is set to 10

2024-10-09 08:50 UTC, akhilmoogi commented on performance-test/README.md
Can we align the categories?

2024-10-09 08:50 UTC, akhilmoogi commented on performance-test/README.md
Kindly add for how many TPS its calculated for, and also for constant throughput timer mention the calculation. Refer resident services read me file for more details in this section.

2024-10-14 06:43 UTC, akhilmoogi commented
@vishwa-vyom Peer review is complete for IDA. Kindly do a final review from your side and merge the PR

2024-10-16 12:42 UTC, vishwa-vyom requested changes
As discussed over call, please check on the below review points.
1. Use base64 encode and decode to kyc bioauth
2. addidentitysetup renaming to freshIdentityCreationCount
3. Maximum and minimum of Counter for different threadgroup
4. Send OTP link dependency preparation phase
5. Authdemo and IDA does not need auth token (only identity requires)
6. No need of calling the get Idrepo since we are using same biometric (Discussion with Varaniya) to avoid pre-requistics -- Authentication with Biometrics
7. Renaming counter naming
8. Authentication with demographics with date of birth, name and gender (instead of gender)
9. Extracted data with lesser size
10. Add identity in readme file
11. Reuse same data in readme file
12. Mention Threadgroup instead of thread and Authentication with Demographics.

2025-01-08 12:56 UTC, akhilmoogi commented
Review points for IDA Script:

1. In CSV config Load face data From File should follow camel case -> Load Face Data From File
2. In Create Identities in MOSIP Identity System (Setup) change Generate Regproc Auth Token Endpoint to -> Authentication Regproc Endpoint
3. In Create Identities in MOSIP Identity System (Setup) change Generate Idrepo Auth Token Endpoint to -> Authentication Idrepo Endpoint
4. In PMS Authentication ValidateToken Endpoint should be -> Validate Token Endpoint (Space in between)
5. In S04 EKYC with Biometrics (Preparation) - Transaction ID Counter, change the variable name from tranIdAwb to a different one, as the same variable name is used in S02 Authentication with Biometrics (Preparation)

2025-01-08 12:59 UTC, akhilmoogi commented on performance-test/README.md
> +	* Third Party Certificates (Setup) : This threadgroup contains series of certificate upload to support the IDA execution.
It should be certificates

2025-01-09 11:42 UTC, akhilmoogi commented on performance-test/README.md
> +* The script and the below calculation is preconfigured as per 100 tps, if you are testing for other tps, the below values neds to be adjusted.
Needs

2025-01-09 11:42 UTC, akhilmoogi commented on performance-test/README.md
> +		* S01 T01 Auth Send OTP : This thread sends OTP request.
thread to API endpoint

2025-01-10 08:06 UTC, akhilmoogi commented
@nihallakshmankonchady PR review is complete from my side. All requested changes are now done.
@vishwa-vyom I have reviewed the PR from my side. Kindly review once from your side and merge it.

2025-01-17 08:03 UTC, akhilmoogi commented
@nihallakshmankonchady as per our discussion over a call, kindly update the suggested changes to the script and read me file.

2025-01-21 10:29 UTC, vishwa-vyom approved these changes

2025-01-21 10:41 UTC, nihallakshmankonchady commented on performance-test/README.md
> +		* S01 T01 Auth Send OTP : This thread sends OTP request.
@akhilmoogi .. 
changed it to API endpoint

2025-01-21 10:41 UTC, nihallakshmankonchady commented on performance-test/README.md
> +* The script and the below calculation is preconfigured as per 100 tps, if you are testing for other tps, the below values neds to be adjusted.
@akhilmoogi . Changed to Needs

2025-01-21 10:42 UTC, nihallakshmankonchady commented on performance-test/README.md
> +	* Third Party Certificates (Setup) : This threadgroup contains series of certificate upload to support the IDA execution.
@akhilmoogi .. Changed to certificates

2025-01-21 12:09 UTC, akhilmoogi commented on performance-test/README.md
> +		* S01 T01 Auth Send OTP : This thread sends OTP request.
Corrected

2025-01-21 12:09 UTC, akhilmoogi commented on performance-test/README.md
> +	* Third Party Certificates (Setup) : This threadgroup contains series of certificate upload to support the IDA execution.
corrected

2025-01-21 12:10 UTC, akhilmoogi commented on performance-test/README.md
> +* The script and the below calculation is preconfigured as per 100 tps, if you are testing for other tps, the below values neds to be adjusted.
corrected

2025-01-21 13:12 UTC, merged