MOSIP-35176 Removed spring boot 2
mosip/id-authentication pull request #1374
Opened 2024-11-07 08:47 UTC by kameshsr

2024-11-07 09:01 UTC, ashok-ksharma approved these changes

2024-11-11 11:51 UTC, ashok-ksharma requested changes

2024-11-11 11:51 UTC, ashok-ksharma commented on authentication/authentication-common/src/main/java/io/mosip/authentication/common/service/integration/NotificationManager.java
> -import io.mosip.idrepository.core.exception.RestServiceException;
Why this import statement additional and deletion is there?

2024-11-11 12:09 UTC, closed without merging

2024-11-11 12:10 UTC, kameshsr commented
https://github.com/mosip/id-authentication/pull/1376
will add this PR change to this PR