MOSIP-17300
mosip/id-authentication pull request #581
Opened 2021-10-19 04:52 UTC by NagarjunaKuchi

splitting biometrics based on type and sub type

2021-10-19 15:26 UTC, loganathan-sekaran requested changes

2021-10-19 15:26 UTC, loganathan-sekaran commented on authentication/authentication-common/src/main/java/io/mosip/authentication/common/service/facade/AuthFacadeImpl.java
> +		return List.of(type + "_" + SingleAnySubtypeType.LEFT.value() + " " + SingleAnySubtypeType.THUMB.value(),
Instead of concatenating like type directly as string, please get its value and concatenate.

2021-10-19 15:26 UTC, loganathan-sekaran commented on authentication/authentication-common/src/main/java/io/mosip/authentication/common/service/facade/AuthFacadeImpl.java
> +			Collections.emptyList();
You need to return the empty collection in the default case. Remove the return statement outside the swtich case.

2021-10-19 15:26 UTC, LoganathanSekar7627 commented on authentication/authentication-common/src/main/java/io/mosip/authentication/common/service/impl/IdServiceImpl.java
> +					bioFilterAttributes.forEach(attribute -> Optional.ofNullable(bioDataMap.get(attribute))
Use map collector instead of for each.

2021-10-19 15:26 UTC, LoganathanSekar7627 commented on authentication/authentication-common/src/main/java/io/mosip/authentication/common/service/impl/idevent/CredentialStoreServiceImpl.java
> +				.collect(Collectors.partitioningBy(entry -> entry.getKey().startsWith(BiometricType.FINGER.value())
Check with a case insensitive way

2021-10-19 15:26 UTC, LoganathanSekar7627 commented on authentication/authentication-core/src/main/java/io/mosip/authentication/core/constant/IdAuthConfigKeyConstants.java
> -	public static final String CREDENTIAL_BIOMETRIC_ATTRIBUTE_NAME = "mosip.ida.credential.biometric.attribute.name";
Please remove the property from config also.

2021-10-19 15:26 UTC, LoganathanSekar7627 commented on authentication/authentication-core/src/main/java/io/mosip/authentication/core/spi/id/service/IdService.java
> +	Map<String, Object> getIdByUin(String uin, boolean isBio, List<String> bioFilterAttributes) throws IdAuthenticationBusinessException;
Please make sure you change the list to set either in this PR or in next.

2021-10-20 04:16 UTC, NagarjunaKuchi commented on authentication/authentication-core/src/main/java/io/mosip/authentication/core/constant/IdAuthConfigKeyConstants.java
> -	public static final String CREDENTIAL_BIOMETRIC_ATTRIBUTE_NAME = "mosip.ida.credential.biometric.attribute.name";
Removed from config.
[https://github.com/mosip/mosip-config/pull/982](https://github.com/mosip/mosip-config/pull/982)

2021-10-20 04:55 UTC, LoganathanSekar7627 approved these changes

2021-10-20 09:08 UTC, loganathan-sekaran approved these changes

2021-10-20 09:12 UTC, merged